/**
 * Agent onboarding orchestrator (spec §10, signing path 2 of §5.5).
 *
 * SignBox signs NOTHING here — the superior authority signs the ESR in its
 * own wallet (INV-005). This module owns the local orchestration and its two
 * security-critical properties:
 *
 * - **Secret persistence order (§10.3):** the key is generated, immediately
 *   sealed in a *temporary* encrypted container (passphrase set BEFORE the
 *   ESR), and only promoted to the active keystore AFTER on-chain
 *   confirmation. A failure, a mismatch, or a timeout destroys the temp
 *   container — the key is never orphaned and never lost.
 * - **Post-landing verification (§10.2 step 12):** before activating the key,
 *   the on-chain result must match exactly what the ESR requested. A
 *   transaction modified in the wallet never activates a key.
 *
 * Everything chain-specific (building actions, encoding the ESR, reading and
 * verifying the chain) lives behind OnboardingBackend so this core is fully
 * testable without a live chain.
 */

import { canonicalize, canonicalSha256Hex } from "../core/canonical/jcs.js";
import { emptyPolicy } from "../core/policy/schema.js";
import { SignBoxError } from "../core/errors.js";
import type { ChainContext, ExportPolicy } from "../core/types.js";
import type { KeystoreMetadata } from "../keystore/encryptedFile.js";

export class OnboardingError extends SignBoxError {
  override readonly name = "OnboardingError";
  constructor(
    readonly code:
      | "AUTHORITY_MISSING"
      | "AGENT_EXISTS"
      | "AGENT_MISSING"
      | "POLICY_EXISTS"
      | "TIMEOUT"
      | "VERIFICATION_FAILED"
      | "ABORTED",
    message: string,
  ) {
    super(message);
  }
}

export type OnboardingMode = "create" | "existing";

export interface OnboardingInput {
  chain: ChainContext;
  authority: string;
  agent: string;
  /** Dedicated agent permission (generated by the caller). */
  permission: string;
  mode: OnboardingMode;
  exportPolicy: ExportPolicy;
  /** Final keystore path; a sibling temp container is used until confirmed. */
  keystorePath: string;
  /** RAM to buy for the new account (mode "create"); paid by the authority. */
  ramBytes?: number;
}

/** A human-readable summary line of one action in the onboarding request. */
export interface ActionSummary {
  contract: string;
  action: string;
  detail: string;
}

export interface BuiltRequest {
  esrUri: string;
  summary: ActionSummary[];
}

export interface VerificationResult {
  ok: boolean;
  reason?: string;
}

/** Chain-specific operations. The XPR implementation lives in xprBackend.ts. */
export interface OnboardingBackend {
  authorityExists(authority: string): Promise<boolean>;
  agentAccountExists(agent: string): Promise<boolean>;
  policyRowExists(agent: string): Promise<boolean>;
  buildRequest(args: {
    input: OnboardingInput;
    agentPublicKey: string;
    emptyPolicyJson: string;
    emptyPolicyHash: string;
  }): Promise<BuiltRequest>;
  /** Poll for the signed onboarding tx to land; resolve null on deadline. */
  waitForConfirmation(agent: string, deadlineMs: number): Promise<{ txid: string } | null>;
  /** Verify the landed on-chain state matches the request exactly (§10.2). */
  verifyLanded(args: {
    input: OnboardingInput;
    agentPublicKey: string;
    emptyPolicyHash: string;
  }): Promise<VerificationResult>;
}

export interface KeystoreOps {
  createTemp(path: string, secret: Buffer, passphrase: Buffer, meta: KeystoreMetadata): void;
  promote(tempPath: string, finalPath: string): void;
  destroy(path: string): void;
}

export interface OnboardingDeps {
  backend: OnboardingBackend;
  generateKey: () => Promise<{ wif: string; publicKey: string }>;
  /** Prompted BEFORE the ESR (§10.3). The flow wipes the returned buffer. */
  getPassphrase: () => Promise<Buffer>;
  keystore: KeystoreOps;
  /** Present the ESR to the authority (QR + URI). */
  present: (request: BuiltRequest) => void;
  now: () => number;
  sessionTimeoutMs?: number;
}

export interface OnboardingResult {
  agent: string;
  authority: string;
  permission: string;
  publicKey: string;
  keystorePath: string;
  exportPolicy: ExportPolicy;
  txid: string;
}

/** 2 minutes — the XPR mobile/web wallet signing window. */
const DEFAULT_SESSION_TIMEOUT_MS = 120_000;

export async function runOnboarding(
  input: OnboardingInput,
  deps: OnboardingDeps,
): Promise<OnboardingResult> {
  const sessionTimeoutMs = deps.sessionTimeoutMs ?? DEFAULT_SESSION_TIMEOUT_MS;

  // Phase A — preconditions (no network writes).
  if (!(await deps.backend.authorityExists(input.authority))) {
    throw new OnboardingError("AUTHORITY_MISSING", "authority account does not exist");
  }
  const agentExists = await deps.backend.agentAccountExists(input.agent);
  if (input.mode === "create" && agentExists) {
    throw new OnboardingError("AGENT_EXISTS", "agent account already exists");
  }
  if (input.mode === "existing" && !agentExists) {
    throw new OnboardingError("AGENT_MISSING", "agent account does not exist");
  }
  if (await deps.backend.policyRowExists(input.agent)) {
    throw new OnboardingError("POLICY_EXISTS", "a policy already exists for this agent");
  }

  // Phase A — generate the agent key locally and the empty deny-all policy.
  const { wif, publicKey } = await deps.generateKey();
  const policy = emptyPolicy(input.chain.chain, input.chain.chainId);
  const emptyPolicyJson = canonicalize(policy);
  const emptyPolicyHash = canonicalSha256Hex(policy);

  // Phase A' — seal the key in a TEMPORARY container before the ESR (§10.3).
  const tempPath = `${input.keystorePath}.onboarding`;
  const passphrase = await deps.getPassphrase();
  const secret = Buffer.from(wif, "utf8");
  try {
    deps.keystore.createTemp(tempPath, secret, passphrase, {
      publicKey,
      exportPolicy: input.exportPolicy,
      chain: input.chain,
      agent: input.agent,
      permission: input.permission,
      createdAt: new Date(deps.now()).toISOString(),
    });
  } finally {
    secret.fill(0);
    passphrase.fill(0);
  }

  try {
    // Phase B — build and present the ESR; the authority signs in its wallet.
    const request = await deps.backend.buildRequest({
      input,
      agentPublicKey: publicKey,
      emptyPolicyJson,
      emptyPolicyHash,
    });
    deps.present(request);

    // Phase C — wait for confirmation within the session window.
    const confirmation = await deps.backend.waitForConfirmation(
      input.agent,
      deps.now() + sessionTimeoutMs,
    );
    if (confirmation === null) {
      throw new OnboardingError("TIMEOUT", "onboarding was not confirmed in time");
    }

    // Phase C — verify the landed state matches the request exactly (§10.2).
    const verified = await deps.backend.verifyLanded({ input, agentPublicKey: publicKey, emptyPolicyHash });
    if (!verified.ok) {
      throw new OnboardingError(
        "VERIFICATION_FAILED",
        `on-chain result does not match the request${verified.reason ? `: ${verified.reason}` : ""}`,
      );
    }

    // Phase C — promote the key to active only now.
    deps.keystore.promote(tempPath, input.keystorePath);
    return {
      agent: input.agent,
      authority: input.authority,
      permission: input.permission,
      publicKey,
      keystorePath: input.keystorePath,
      exportPolicy: input.exportPolicy,
      txid: confirmation.txid,
    };
  } catch (error) {
    // Any failure (timeout, mismatch, error) destroys the temp container:
    // the key is never activated for an incomplete onboarding (§10.3).
    deps.keystore.destroy(tempPath);
    throw error;
  }
}
